Switch from Jackson to plain JSONObjects for exporting message history
Exporting the message history using Jackson on Android 4.4 leads to the
app crashing with a NoClassDefFoundError.